### PR TITLE
Lab 1/integrate partner experiment data

### PR DESCRIPTION
**Pull request by iberben**

### CODE REVIEW

**Comment by iberben** [comment]
https://github.com/vikingco/mvne-platform/pull/4773

**Comment by Jogazo** [comment]
@jgeskens Can you please review this PR?
Functional testing by @jnsvr , Saskia and Davy has already been finished.

**Comment by jnsvr** [comment]
I poked @jgeskens, he should be reviewing it right now.

**Comment by freeduerinckx** [comment]
Did a pair review with @jgeskens which resulted in one remark: a unit test for 
`handle_multiple_actions(self, method, selected_object_ids, request=None):`
The unit test is being written as I type.

**Comment by Duologic** [comment]
So I guess we should wait for the unittest?

**Comment by freeduerinckx** [comment]
Yes please :-)

**Comment by freeduerinckx** [comment]
If the build passes the it's ready to ship

**Pull request merged**
