### PR TITLE
don't try to sort on __unicode__ method

### PR DESCRIPTION
**Pull request by mrbox**
@jgeskens can you please take a look here? :)

### CODE REVIEW

**Comment by jgeskens** [comment]
Looks fine to me. No little small unit test to make coveralls happy? ;-) If you don't have time, don't worry, then I will at some point unit test it, as part of the 100% coverage goal...

**Comment by mrbox** [comment]
I'll add this test :)

**Comment by jgeskens** [comment]
@mrbox You rock!

**Comment by mrbox** [comment]
@jgeskens 0.37% coverage improved!

**Comment by mrbox** [comment]
@jgeskens can you please merge this branch into master? I need it to move one with other fix :)

**Pull request merged**
