### PR TITLE
optimize generation of csv

### PR DESCRIPTION
**Pull request by mrbox**
@jgeskens can you please review? It was very inefficient.

### CODE REVIEW

**Comment by jgeskens** [comment]
It is the same as the original, because I use the () syntax, so they are generators... what made it more efficient?

**Comment by mrbox** [comment]
But even if they are generators, there is 5 iterations over `lines` - I don't think that using generators will merge 5 loops into 1.

**Comment by jgeskens** [comment]
It collapses to one loop really, it will be more like a pipeline. I still don't see why you felt the need to optimize this code at a very great cost of readability, where the opimization just is a rewriting of the same complexity. Is it because you didn't like what you saw? This is just a typical use of the python pipeline pattern :) If you want to optimize this, at least make use of the csv lib, which works probably dramatically faster and works out escaping details for you :) What do you think?

**Comment by mrbox** [comment]
Well, I just did a small benchmark to compare these two versions and generators version is slower but only about 10-15% slower. So for now I'll close this PR without merging because my initial problem is somewhere else then :)
BTW- I've worked with csv lib quite much before and it's not as good as you think- you need also to hack it sometimes ;)

**Pull request closed without merging**
